### ISSUE TITLE
Links not linking to sections of website

### ISSUE THREAD

**Issue by natalie-macpherson** [kaylinenright/project-night-night#35]
I am not sure if we wanted to have our links to our sections to be set up for this week but currently they are all giving a 404 error. The only pages that are working are the Get Involve page and the Blog/New sections?

**Comment by mystine** [comment]
We should maybe link them

**Comment by natalie-macpherson** [comment]
Yes we should would you like to do it?

**Comment by natalie-macpherson** [comment]
I think they are all linked now. Except for the blog page. @dagerebe I beleive you are doing this so I will close this issue.
